server:
  port: 8080
spring:
  application:
    name: gateway-sandbox
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    config:
      fail-fast: true
    stream:
      bindings:
        fromGatewaySandbox-out-0:
          destination: toJmsSandbox
          content-type: application/json
          group: ${spring.application.name}
      rabbit:
        bindings:
          fromGatewaySandbox-out-0:
            producer:
              transacted: true
              routing-key-expression: headers.JsmSenderRoutingKey
client:
  url:
    address: http://localhost:8081/api/address