spring:
  application:
    name: jms-sandbox
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    config:
      fail-fast: true
    stream:
      bindings:
        fromGatewaySandbox-in-0:
          destination: toJmsSandbox
          content-type: application/json
          group: ${spring.application.name}
          consumer:
            concurrency: 30
      rabbit:
        bindings:
          fromGatewaySandbox-in-0:
            consumer:
              auto-bind-dlq: true
              republish-to-dlq: true
              transacted: true
              binding-routing-key: jms-sandbox